[gcp_service_account]
type = "service_account"
project_id = "streamlit-473702"
private_key_id = "d7dba0523f00aced0f6a1c700f48bbae83134379"
private_key = """
-----BEGIN PRIVATE KEY-----
MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCpQTcOBjqtbQhh
MV/eLnWRGoxXgi5fBid7Ao6U/zPb9lpMlYfF0JPJ2fmss0Wu/w5hBA6xsEm8pFAp
75586GLNsEYEVNwbCCXm19Cbf9CnoF4T0iMKy5WilXETSC5vzn3P3fPzyp4QqvJP
xkxnHlPcZMp8YdI80pmybDvhlvIhrkET7dzumZ+/VVzeNiS2exaSq/aWLuqBqgQC
2jqw9UBkOodZRFavwW3Wf7/8lTZ0AHaepz/HWEFDiGSh52q1bsD9h23mvUsmEzAy
SEfSPhdt8cFHIQIJ52NEkiX1ymgUaBIMbOGAL32G8bEui1b30wspV/dtl+8AW6nr
wEeGOWdTAgMBAAECggEACce98a6Ed38Ea/FZc9JFcuQQ1gGswkrtvxrvuEZi7cP3
hdNiLBkYYSKaXdNiJHGSmCKO4s+oAyGPjEzPYLJg+zfDY/6vVVSMNCGmaUXifb0z
knujEL2g4Os3xIB4RnetJ3TQ4vaDWb03EUsJITBMckDUvok8h803mmrMrwV06mM6
SPlGoUtk0cVD2q6r+oQie0qm4P1YH2zp8CVy86mY+vLAO5vY0cqACeyddRoqSpOP
bu8Oh5mi3vSM+Xkf64Z/2EYgYUaCzrqkjTAz4qSWWR3fWLyXLAAvV8ObCBVIwCZ2
QGWLBC8jefKFmQs7QSSvBlAMJj9p8gknZidtDHtdeQKBgQDVgUG87djwBAXnQlMK
GU8usvHprf9UTOEiwtVth7wxoYsHBpkNSZZPzQJFHb4A5MWNxYBLg7pMxGKfe1L7
PuGa4EsvcjI5NWl70hX06172j5lIbP5bsM50+649equb1QpJjKE2SBzrWXIXxABd
PU8T28v5NwjoBEA6zWziAPEZjQKBgQDK8UYk1OD9zFb9A8CVXL3JOPMGgl2dUdme
ulkXcg7mTIobPLGctNU1qxOpILVQrzb89aVm3mi45r/VpLbRKxTufrdMfSLCFrDr
NeVSpFJRoL9T1XmoIh1egO8TbYLsmTEj5035HMB12P+7PtFCTihKHN7Feh7Mew16
qD2u8KucXwKBgHbAojPXh2ZYln/+n/lqAmTTG0MCiJX2/PI8tEFr0f05AP8zaEW/
vF8+hBi1Zk1Q8aDdTXKzHhg80y4phgpA+3MNdkQ5nD29u6InRBcqI3O4g2WJWiDd
wrfGlS+U34aZhFNMaQ6sJYmyAoe9eQZjZ2yAQH+pYMbMNn1+bSV3qKKxAoGAW+w/
fm1iX/NPr5kkgUMZv+xowBkKuDib3va/ZgxGzW/72mx6cuXB8WZFKIVlO1+yA5Bs
1BSH0MDMQcQy/rmJ6KFC+4Vu2gUXK+MktXMyykCKiTmXul2Beg3ivKUM+YhGJuId
gmnQj1C0PSct99+ZBkDfcwlmq+5M47MTBYuD3/cCgYEA0UNKmznFgqF3hqV8ATDX
bmJ/liTFwq0gJEdCSA0bs6yKXaHrkVWtMiI9jtz/agzhVhvZnn27VwNuiownn3NG
hk4/fsICo46dExJbsbWuSIl/jmop0MT1uZoiEQocg2o2nxweOHjlIcRcmJUVR85R
kcYeEyx78qC12ru5ei2I/KI=
-----END PRIVATE KEY-----
"""
client_email = "gsheet-python-access@streamlit-473702.iam.gserviceaccount.com"
client_id = "105256044297607091314"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/gsheet-python-access%40streamlit-473702.iam.gserviceaccount.com"
universe_domain = "googleapis.com"